[package]
  edition = "2024"
  name    = "microbit"
  version = "0.1.0"

[dependencies]
  cortex-m         = { version = "0.7.8", features = ["critical-section-single-core"] }
  cortex-m-rt      = "0.7.6"
  embedded-hal     = "1.0.0"
  heapless         = "0.9.3"
  microbit         = "0.16.0"
  panic-halt       = "1.0.0"
  panic-rtt-target = { version = "0.2.0" }
  rtt-target       = { version = "0.6.2" }
  tinyrand         = "0.5.0"
