//! A lightweight `App`/`Plugin` shell on top of the concrete `World`.
//!
//! Mirrors the ergonomic surface of `bevy_app` without its heavyweight
//! sub-app/schedule-manager machinery. `App<W>` is a thin owner of a generated
//! [`World`](crate::world::WorldApi) that exposes builder methods for
//! resources, schedules, systems and plugins; once built, the application code
//! drives the runner loop itself, calling `world.run_schedule(label)` and
//! `world.flush_commands()` at the cadences it chooses. This keeps scheduling
//! fully programmatic and hardware-agnostic.

use crate::commands_buffer::CommandBuffer;
use crate::schedule::ScheduleLabel;
use crate::system::{IntoSystem, ResourceInsRef};
use crate::world::WorldApi;

/// Extension point mirroring Bevy's `Plugin`.
///
/// A plugin's [`Plugin::build`] registers resources, schedules and systems on
/// the [`App`] it receives. `W` is the concrete `World` type generated by
/// `define_world!`; the label supertrait bound lets platform plugins reach for
/// the standard schedules by name.
pub trait Plugin<W: WorldApi> {
    /// Registers resources, schedules and systems with the [`App`].
    fn build(&self, app: &mut App<W>);
}

/// The status code returned by a runner when it exits.
///
/// Mirrors Bevy's `AppExit`. Most embedded runners never return (they loop
/// forever), but the type lets desktop runners signal graceful termination.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AppExit {
    /// The runner completed successfully.
    Success,
    /// The runner encountered a fatal error.
    Error,
}

/// The embedded application owner, wrapping a single concrete `World`.
pub struct App<W: WorldApi> {
    /// The underlying world holding all resources, entities and schedules.
    world: W,
}

impl<W: WorldApi> App<W> {
    /// Wraps an already-constructed `World` in the application shell.
    pub fn new(world: W) -> Self {
        Self { world }
    }

    /// Consumes the app and returns the underlying `World`, so the developer
    /// can drive its runner loop directly.
    pub fn into_world(self) -> W {
        self.world
    }

    /// Returns an immutable borrow of the underlying world.
    pub fn world(&self) -> &W {
        &self.world
    }

    /// Returns a mutable borrow of the underlying world.
    pub fn world_mut(&mut self) -> &mut W {
        &mut self.world
    }

    /// Inserts a resource, writing it into the world's resource slot.
    pub fn insert_resource<R: 'static>(&mut self, resource: R) -> &mut Self
    where
        W: ResourceInsRef<R>,
    {
        self.world.insert_resource(resource);
        self
    }

    /// Adds a schedule under label `L` if it does not already exist.
    pub fn add_schedule<L: ScheduleLabel>(&mut self, label: L) -> &mut Self {
        self.world.add_schedule(label);
        self
    }

    /// Adds a system to the schedule identified by label `L`.
    pub fn add_system<L: ScheduleLabel, S: IntoSystem<W>>(&mut self, label: L, system: S) -> &mut Self {
        self.world.add_system(label, system.into_system());
        self
    }

    /// Registers a single plugin.
    pub fn add_plugin<P: Plugin<W>>(&mut self, plugin: P) -> &mut Self {
        plugin.build(self);
        self
    }

    /// Runs the schedule identified by label `L`, then drains the deferred
    /// command buffer. Convenience for the developer-provided runner loop.
    pub fn run_schedule_and_flush<L: ScheduleLabel>(&mut self, label: L) {
        self.world.run_schedule(label);
        self.world.flush_commands();
    }

    /// Consumes the app and passes the world to a runner function that owns the
    /// main loop. Mirrors Bevy's `App::run`, but the runner is supplied by the
    /// caller (e.g. `bevy_microbit::microbit_runner`) so scheduling stays
    /// programmatic and hardware-agnostic.
    ///
    /// The runner returns [`AppExit`]; most embedded runners loop forever and
    /// never actually produce a value, so the caller can follow the call with
    /// `unreachable!()`.
    pub fn run<F>(&mut self, runner: F) -> AppExit
    where
        F: FnOnce(&mut W) -> AppExit,
    {
        runner(&mut self.world)
    }

    /// Returns a raw pointer to the world's command buffer (for advanced
    /// systems that construct `Commands` themselves).
    pub fn commands_ptr(&mut self) -> *mut CommandBuffer {
        self.world.commands_ptr()
    }
}

/// Sealed tuple marker for `add_plugins` group registration, mirroring Bevy's
/// plugin groups.
pub trait Plugins<W: WorldApi> {
    /// Adds every contained plugin to the app, in order.
    fn add(self, app: &mut App<W>);
}

impl<W: WorldApi> Plugins<W> for () {
    fn add(self, _app: &mut App<W>) {}
}

macro_rules! impl_plugins_tuple {
    ($($p:ident),+) => {
        impl<W: WorldApi, $($p: Plugin<W>),+> Plugins<W> for ($($p,)+) {
            #[allow(non_snake_case)]
            fn add(self, app: &mut App<W>) {
                let ($($p,)+) = self;
                $(app.add_plugin($p);)+
            }
        }
    };
}

impl_plugins_tuple!(A, B);
impl_plugins_tuple!(A, B, C);
impl_plugins_tuple!(A, B, C, D);
impl_plugins_tuple!(A, B, C, D, E);
impl_plugins_tuple!(A, B, C, D, E, F);
impl_plugins_tuple!(A, B, C, D, E, F, G);
impl_plugins_tuple!(A, B, C, D, E, F, G, H);