//! System param plumbing: marker traits, [`Res`]/[`ResMut`] wrappers, the
//! [`Query`] iterator and its [`Fetch`] implementations, [`ScheduleLabel`],
//! and the [`IntoSystem`] glue.
//!
//! The concrete `World` is generated by the `define_world!` macro per app; it
//! implements [`ColumnRef<T>`], [`ResourceRef<R>`] and [`CommandsRef`] for each
//! registered component/resource. The `#[system]` macro expands a Bevy-style
//! function into a generic `fn(&mut W)` whose bound list pins those types; at
//! `app.add_system` time the generic specialises to the app's `World`.
//!
//! Borrow-splitting between query params is achieved by storing raw column
//! pointers in [`Fetch::State`] rather than `&mut W` borrows, so multiple
//! queries mutated in the same system are reconstructed from disjoint slots.
//! Items are reconstructed with the world's lifetime `'w` (not the iterator
//! borrow), so a mutable iterator yields non-overlapping `&'w mut T` per index
//! without tripping the streaming-iterator limitation.

use core::marker::PhantomData;

use crate::column::ColumnOps;
use crate::commands_buffer::CommandBuffer;
use crate::entity::Entity;
use crate::Resource;

// =====================================================================
// --- Traits bridging the concrete `World` and column accessors -------

/// Column access for a component type `T`.
///
/// Implemented automatically for the concrete `World` by `define_world!` for
/// every registered component. All accessors take a raw `*mut Self` pointer
/// (never a `&self`/`&mut self` borrow) so a single `*mut World` can be split
/// into disjoint column borrows by the `#[system]` macro without the borrow
/// checker refusing the second `&mut World`.
pub trait ColumnRef<T: 'static>: Sized {
    /// Returns a raw `*const` pointer to the column.
    ///
    /// # Safety
    /// `world` must be a valid `*mut Self` for at least the lifetime of the
    /// returned pointer's intended use.
    unsafe fn col_ref_raw(world: *mut Self) -> *const dyn ColumnOps<T>;
    /// Returns a raw `*mut` pointer to the column.
    ///
    /// # Safety
    /// Same as [`ColumnRef::col_ref_raw`]; the caller must ensure no aliasing.
    unsafe fn col_mut_raw(world: *mut Self) -> *mut dyn ColumnOps<T>;
    /// Returns the column's capacity.
    ///
    /// # Safety
    /// `world` must be a valid `*mut Self`.
    unsafe fn col_capacity(world: *mut Self) -> usize;
}

/// Resource access for a resource type `R`.
///
/// Like [`ColumnRef`], accessors take a raw `*mut Self` for borrow-splitting.
pub trait ResourceRef<R: 'static>: Sized {
    /// Returns a raw `*const` pointer to the resource slot (`null` when
    /// absent).
    ///
    /// # Safety
    /// `world` must be a valid `*mut Self`.
    unsafe fn res_ref_raw(world: *mut Self) -> *const R;
    /// Returns a raw `*mut` pointer to the resource slot (`null` when
    /// absent).
    ///
    /// # Safety
    /// `world` must be a valid `*mut Self`.
    unsafe fn res_mut_raw(world: *mut Self) -> *mut R;
}

/// Synchronous resource insertion.
///
/// Implemented for each registered resource by `define_world!`; writing the
/// `R` slot is disjoint from any column borrow, so `Commands::insert_resource`
/// can run inside a system that also holds queries.
pub trait ResourceInsRef<R: 'static>: Sized {
    /// Installs `value` as the resource `R`.
    ///
    /// # Safety
    /// `world` must be a valid `*mut Self`.
    unsafe fn insert_resource(world: *mut Self, value: R);
}


/// This trait will be implemeted for any world
pub trait HasResource<R: 'static>: ResourceRef<R> + ResourceInsRef<R> {}
impl <R: 'static, W: ResourceRef<R> + ResourceInsRef<R>> HasResource<R> for W {}


/// Typed spawn-queue access for a component `T`.
///
/// Implemented for each registered component by `define_world!`. The `World`
/// carries a per-component pending spawn queue (a distinct field from the
/// column itself), so enqueuing a spawn while a `Query<&T>` borrows the column
/// immutably stays sound.
pub trait SpawnRef<T: 'static>: Sized {
    /// Allocates an entity id and enqueues `value` to be inserted on the next
    /// [`WorldApi::flush_commands`](crate::world::WorldApi::flush_commands).
    ///
    /// # Safety
    /// `world` must be a valid `*mut Self`.
    unsafe fn enqueue_spawn(world: *mut Self, value: T) -> Entity;
}

/// Command-buffer access for the [`Commands`](crate::commands::Commands) param.
pub trait CommandsRef: Sized {
    /// Returns a raw `*mut` pointer to the world's command buffer.
    ///
    /// # Safety
    /// `world` must be a valid `*mut Self`.
    unsafe fn commands_raw(world: *mut Self) -> *mut CommandBuffer;
}

// =====================================================================
// --- Resources --------------------------------------------------------

/// A shared immutable view of a [`Resource`], mirroring Bevy's `Res`.
pub struct Res<'a, R: Resource> {
    /// The borrowed resource value.
    value: &'a R,
}

impl<'a, R: Resource> Res<'a, R> {
    /// Creates a `Res` from a borrow.
    pub const fn new(value: &'a R) -> Self {
        Self { value }
    }
}

impl<R: Resource> core::ops::Deref for Res<'_, R> {
    type Target = R;
    fn deref(&self) -> &R {
        self.value
    }
}

/// An exclusive mutable view of a [`Resource`], mirroring Bevy's `ResMut`.
pub struct ResMut<'a, R: Resource> {
    /// The borrowed resource value.
    value: &'a mut R,
}

impl<'a, R: Resource> ResMut<'a, R> {
    /// Creates a `ResMut` from a mutable borrow.
    pub fn new(value: &'a mut R) -> Self {
        Self { value }
    }
}

impl<R: Resource> core::ops::Deref for ResMut<'_, R> {
    type Target = R;
    fn deref(&self) -> &R {
        self.value
    }
}

impl<R: Resource> core::ops::DerefMut for ResMut<'_, R> {
    fn deref_mut(&mut self) -> &mut R {
        self.value
    }
}

// =====================================================================
// --- Query / Fetch ----------------------------------------------------

/// A query over one or more component columns of a concrete `World` `W`.
///
/// Constructed by the `#[system]` macro from a raw world pointer; iteration
/// yields [`Fetch::Item`] with the world's lifetime `'w` for every entity that
/// has all requested components. Supported parameter shapes mirror the Bevy
/// patterns the game uses: `&T`, `&mut T`, `(Entity, &T)`, `(Entity, &mut T)`,
/// and the two-component tuples `(&T, &U)`, `(&mut T, &mut U)`, `(&T, &mut U)`.
pub struct Query<'w, F: Fetch<'w, W> + 'w, W> {
    /// Opaque column-reference state captured at construction (raw pointers).
    state: F::State,
    /// Iteration bound = the minimum capacity of participating columns.
    cap: usize,
    /// The next index to probe during iteration.
    idx: usize,
    /// Ties `'w` to the world borrow.
    _life: PhantomData<&'w W>,
}

impl<'w, F: Fetch<'w, W> + 'w, W> Query<'w, F, W> {
    /// Builds a query from a raw world pointer.
    ///
    /// # Safety
    /// `world` must be a valid `*mut W` whose columns outlive the query, and
    /// callers must ensure no aliasing rules are violated across concurrently
    /// held queries derived from the same world.
    pub unsafe fn from_world(world: *mut W) -> Self {
        // SAFETY: caller guarantees `world` is valid for `'w`.
        let (state, cap) = unsafe { F::make_state(world) };
        Self {
            state,
            cap,
            idx: 0,
            _life: PhantomData,
        }
    }

    /// Returns the matching component(s) for the single entity that has the
    /// queried components, mirroring Bevy's `Query::single`.
    pub fn single(&self) -> Result<F::Item<'w>, ()> {
        for i in 0..self.cap {
            if let Some(item) = F::fetch(&self.state, i) {
                return Ok(item);
            }
        }
        Err(())
    }

    /// Returns a mutable view of the matching component(s) for the single
    /// entity, mirroring Bevy's `Query::single_mut`.
    pub fn single_mut(&mut self) -> Result<F::Item<'w>, ()> {
        for i in 0..self.cap {
            if let Some(item) = F::fetch_mut(&mut self.state, i) {
                return Ok(item);
            }
        }
        Err(())
    }

    /// Returns an iterator over the populated matches (immutable views).
    pub fn iter(&self) -> QueryIter<'_, 'w, F, W> {
        QueryIter {
            state: &self.state,
            cap: self.cap,
            idx: 0,
            _life: PhantomData,
        }
    }

    /// Returns an iterator over the populated matches (mutable views).
    pub fn iter_mut(&mut self) -> QueryIterMut<'_, 'w, F, W> {
        QueryIterMut {
            state: &mut self.state,
            cap: self.cap,
            idx: 0,
            _life: PhantomData,
        }
    }
}

/// Immutable iterator produced by [`Query::iter`] / `for x in &query`.
///
/// Borrows the query's state immutably; items carry the world lifetime `'w`.
pub struct QueryIter<'s, 'w, F: Fetch<'w, W> + 'w, W> {
    /// Borrow of the query's state.
    state: &'s F::State,
    /// Iteration bound.
    cap: usize,
    /// The next index to probe.
    idx: usize,
    /// Ties `'w` to the world.
    _life: PhantomData<&'w W>,
}

impl<'s, 'w, F: Fetch<'w, W> + 'w, W> Iterator for QueryIter<'s, 'w, F, W> {
    type Item = F::Item<'w>;
    fn next(&mut self) -> Option<Self::Item> {
        while self.idx < self.cap {
            let i = self.idx;
            self.idx += 1;
            if let Some(item) = F::fetch(self.state, i) {
                return Some(item);
            }
        }
        None
    }
}

impl<'s, 'w, F: Fetch<'w, W> + 'w, W> IntoIterator for &'s Query<'w, F, W> {
    type Item = F::Item<'w>;
    type IntoIter = QueryIter<'s, 'w, F, W>;
    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

/// Mutable iterator produced by [`Query::iter_mut`] / `for x in &mut query`.
///
/// Borrows the query's state mutably for the cursor, but yielded items carry
/// the world lifetime `'w` (reconstructed from raw column pointers), so each
/// `next()` call returns a fresh non-overlapping `&'w mut T`.
pub struct QueryIterMut<'s, 'w, F: Fetch<'w, W> + 'w, W> {
    /// Mutable borrow of the query's state (only the cursor mutates).
    state: &'s mut F::State,
    /// Iteration bound.
    cap: usize,
    /// The next index to probe.
    idx: usize,
    /// Ties `'w` to the world.
    _life: PhantomData<&'w W>,
}

impl<'s, 'w, F: Fetch<'w, W> + 'w, W> Iterator for QueryIterMut<'s, 'w, F, W> {
    type Item = F::Item<'w>;
    fn next(&mut self) -> Option<Self::Item> {
        while self.idx < self.cap {
            let i = self.idx;
            self.idx += 1;
            if let Some(item) = F::fetch_mut(self.state, i) {
                return Some(item);
            }
        }
        None
    }
}

impl<'s, 'w, F: Fetch<'w, W> + 'w, W> IntoIterator for &'s mut Query<'w, F, W> {
    type Item = F::Item<'w>;
    type IntoIter = QueryIterMut<'s, 'w, F, W>;
    fn into_iter(self) -> Self::IntoIter {
        self.iter_mut()
    }
}

/// How a [`Query`] obtains row data from the concrete `World` `W`.
///
/// Each supported query parameter shape implements `Fetch`; the impl owns raw
/// column pointers in [`State`] and yields [`Item`] per matching entity.
///
/// # Safety
/// Implementors must store only raw pointers derived from a single `*mut W`
/// and reconstruct disjoint references in `fetch`/`fetch_mut` carrying the
/// `'w` lifetime (the world's).
pub unsafe trait Fetch<'w, W> {
    /// The state captured at construction time (column pointers etc.).
    type State;
    /// The item yielded per matching entity, borrowing the world for `'w`.
    type Item<'i>
    where
        Self: 'w;

    /// Builds the state from a raw world pointer; returns it plus the
    /// iteration capacity (the minimum column capacity participating).
    ///
    /// # Safety
    /// `world` must point to a valid `W` for `'w`.
    unsafe fn make_state(world: *mut W) -> (Self::State, usize);

    /// Fetches the item at `index`, if the entity matches.
    fn fetch(state: &Self::State, index: usize) -> Option<Self::Item<'w>>;
    /// Fetches the mutable item at `index`, if the entity matches.
    fn fetch_mut(state: &mut Self::State, index: usize) -> Option<Self::Item<'w>> {
        Self::fetch(state, index)
    }
}

// --------------------- Concrete Fetch implementations ----------------

// `&T` — immutable single-component query.
unsafe impl<'w, T: 'static, W: ColumnRef<T>> Fetch<'w, W> for &'w T {
    type State = *const dyn ColumnOps<T>;
    type Item<'i>
        = &'i T
    where
        Self: 'w;

    unsafe fn make_state(world: *mut W) -> (Self::State, usize) {
        // SAFETY: caller guarantees `world` is valid for `'w`.
        let col = unsafe { <W as ColumnRef<T>>::col_ref_raw(world) };
        // SAFETY: reading capacity is immutable and `col` is valid for `'w`.
        let cap = unsafe { (&*col).capacity() };
        (col, cap)
    }

    fn fetch(state: &Self::State, index: usize) -> Option<Self::Item<'w>> {
        // Copy the raw pointer out without keeping a borrow of `state`.
        let ptr: *const dyn ColumnOps<T> = *state;
        // SAFETY: the column is valid for `'w`; each slot is disjoint.
        let col: &'w dyn ColumnOps<T> = unsafe { &*ptr };
        col.get(index)
    }
}

// `&mut T` — mutable single-component query.
unsafe impl<'w, T: 'static, W: ColumnRef<T>> Fetch<'w, W> for &'w mut T {
    type State = *mut dyn ColumnOps<T>;
    type Item<'i>
        = &'i mut T
    where
        Self: 'w;

    unsafe fn make_state(world: *mut W) -> (Self::State, usize) {
        // SAFETY: caller guarantees `world` is valid for `'w`.
        let col = unsafe { <W as ColumnRef<T>>::col_mut_raw(world) };
        let cap = unsafe { (&*col).capacity() };
        (col, cap)
    }

    fn fetch(_state: &Self::State, _index: usize) -> Option<Self::Item<'w>> {
        // An immutable fetch on a `&mut T` query is intentionally unsupported;
        // returning `None` keeps `single`/`iter` sound on that path.
        None
    }

    fn fetch_mut(state: &mut Self::State, index: usize) -> Option<Self::Item<'w>> {
        // Read the raw pointer out, releasing the borrow of `state`.
        let ptr: *mut dyn ColumnOps<T> = *state;
        // SAFETY: valid for `'w`; slots at distinct indices are disjoint.
        let col: &'w mut dyn ColumnOps<T> = unsafe { &mut *ptr };
        col.get_mut(index)
    }
}

/// Paired column-pointer state for two-component queries.
pub struct PairState<A, B> {
    /// First column state.
    pub a: A,
    /// Second column state.
    pub b: B,
}

// `(&T, &U)` — two immutable components.
unsafe impl<'w, T: 'static, U: 'static, W: ColumnRef<T> + ColumnRef<U>> Fetch<'w, W>
    for (&'w T, &'w U)
{
    type State = PairState<*const dyn ColumnOps<T>, *const dyn ColumnOps<U>>;
    type Item<'i>
        = (&'i T, &'i U)
    where
        Self: 'w;

    unsafe fn make_state(world: *mut W) -> (Self::State, usize) {
        let a = unsafe { <W as ColumnRef<T>>::col_ref_raw(world) };
        let b = unsafe { <W as ColumnRef<U>>::col_ref_raw(world) };
        let cap = unsafe { (&*a).capacity().min((&*b).capacity()) };
        (PairState { a, b }, cap)
    }

    fn fetch(state: &Self::State, index: usize) -> Option<Self::Item<'w>> {
        let col_a: &'w dyn ColumnOps<T> = unsafe { &*state.a };
        let col_b: &'w dyn ColumnOps<U> = unsafe { &*state.b };
        Some((col_a.get(index)?, col_b.get(index)?))
    }
}

// `(&mut T, &mut U)` — two mutable components of distinct types.
unsafe impl<'w, T: 'static, U: 'static, W: ColumnRef<T> + ColumnRef<U>> Fetch<'w, W>
    for (&'w mut T, &'w mut U)
{
    type State = PairState<*mut dyn ColumnOps<T>, *mut dyn ColumnOps<U>>;
    type Item<'i>
        = (&'i mut T, &'i mut U)
    where
        Self: 'w;

    unsafe fn make_state(world: *mut W) -> (Self::State, usize) {
        let a = unsafe { <W as ColumnRef<T>>::col_mut_raw(world) };
        let b = unsafe { <W as ColumnRef<U>>::col_mut_raw(world) };
        let cap = unsafe { (&*a).capacity().min((&*b).capacity()) };
        (PairState { a, b }, cap)
    }

    fn fetch(_state: &Self::State, _index: usize) -> Option<Self::Item<'w>> {
        None
    }

    fn fetch_mut(state: &mut Self::State, index: usize) -> Option<Self::Item<'w>> {
        let col_a: &'w mut dyn ColumnOps<T> = unsafe { &mut *state.a };
        let col_b: &'w mut dyn ColumnOps<U> = unsafe { &mut *state.b };
        Some((col_a.get_mut(index)?, col_b.get_mut(index)?))
    }
}

// `(&T, &mut U)` — mixed mutability two-component query.
unsafe impl<'w, T: 'static, U: 'static, W: ColumnRef<T> + ColumnRef<U>> Fetch<'w, W>
    for (&'w T, &'w mut U)
{
    type State = PairState<*const dyn ColumnOps<T>, *mut dyn ColumnOps<U>>;
    type Item<'i>
        = (&'i T, &'i mut U)
    where
        Self: 'w;

    unsafe fn make_state(world: *mut W) -> (Self::State, usize) {
        let a = unsafe { <W as ColumnRef<T>>::col_ref_raw(world) };
        let b = unsafe { <W as ColumnRef<U>>::col_mut_raw(world) };
        let cap = unsafe { (&*a).capacity().min((&*b).capacity()) };
        (PairState { a, b }, cap)
    }

    fn fetch(_state: &Self::State, _index: usize) -> Option<Self::Item<'w>> {
        None
    }

    fn fetch_mut(state: &mut Self::State, index: usize) -> Option<Self::Item<'w>> {
        let col_a: &'w dyn ColumnOps<T> = unsafe { &*state.a };
        let col_b: &'w mut dyn ColumnOps<U> = unsafe { &mut *state.b };
        Some((col_a.get(index)?, col_b.get_mut(index)?))
    }
}

/// `(Entity, &T)` — drives iteration off `T`'s column.
pub struct EntityRefState<T: 'static> {
    /// The driving column pointer.
    pub col: *const dyn ColumnOps<T>,
}

unsafe impl<'w, T: 'static, W: ColumnRef<T>> Fetch<'w, W> for (Entity, &'w T) {
    type State = EntityRefState<T>;
    type Item<'i>
        = (Entity, &'i T)
    where
        Self: 'w;

    unsafe fn make_state(world: *mut W) -> (Self::State, usize) {
        let col = unsafe { <W as ColumnRef<T>>::col_ref_raw(world) };
        let cap = unsafe { (&*col).capacity() };
        (EntityRefState { col }, cap)
    }

    fn fetch(state: &Self::State, index: usize) -> Option<Self::Item<'w>> {
        let col: &'w dyn ColumnOps<T> = unsafe { &*state.col };
        let t = col.get(index)?;
        Some((Entity::new(index as u32), t))
    }
}

/// `(Entity, &mut T)` — drives iteration off `T`'s column, mutably.
pub struct EntityMutState<T: 'static> {
    /// The driving column pointer.
    pub col: *mut dyn ColumnOps<T>,
}

unsafe impl<'w, T: 'static, W: ColumnRef<T>> Fetch<'w, W> for (Entity, &'w mut T) {
    type State = EntityMutState<T>;
    type Item<'i>
        = (Entity, &'i mut T)
    where
        Self: 'w;

    unsafe fn make_state(world: *mut W) -> (Self::State, usize) {
        let col = unsafe { <W as ColumnRef<T>>::col_mut_raw(world) };
        let cap = unsafe { (&*col).capacity() };
        (EntityMutState { col }, cap)
    }

    fn fetch(_state: &Self::State, _index: usize) -> Option<Self::Item<'w>> {
        None
    }

    fn fetch_mut(state: &mut Self::State, index: usize) -> Option<Self::Item<'w>> {
        let col: &'w mut dyn ColumnOps<T> = unsafe { &mut *state.col };
        let t = col.get_mut(index)?;
        Some((Entity::new(index as u32), t))
    }
}

// =====================================================================
// --- Systems & schedules ----------------------------------------------

/// A type-erased system operating on `*mut ()` storage.
pub type System = fn(*mut ());

/// Converts a `#[system]` function into a [`System`] specialised to `W`.
pub trait IntoSystem<W> {
    /// Returns the type-erased callable bound to world type `W`.
    fn into_system(self) -> System;
}