[package]
name = "bevy_microbit"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A no_std Bevy backend for the BBC micro:bit V1 (nRF51822), exposing an API mirroring official Bevy."

[dependencies]
tiny_ecs.workspace = true
tiny_ecs_macros.workspace = true
cortex-m.workspace = true
cortex-m-rt = "0.7.6"
embedded-hal.workspace = true
microbit.workspace = true
rtt-target.workspace = true
tinyrand.workspace = true

[lints]
workspace = true
